spring:
  threads:
    virtual:
      enabled: true
  application.name: spring-batch-partitioning
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch_partitioning?useSSL=false&connectionTimeZone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 40
      connectionTimeout: 10000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  exposed:
    generate-ddl: false
    show-sql: false
